### ISSUE TITLE
Date and time of sending

### ISSUE THREAD

**Issue by nclm** [jolicode/secret-santa#102]
It would be nice to have an option to select the date and time when the messages will be sent to everyone. I'd love to be able to set up my Secret Santa now, and have it run on Friday at 6 pm for instance. So that it can be planned for a company event without having to go back behind the computer and set up everything at the last minute.

**Comment by pyrech** [comment]
That would be a nice addition, but sadly, it would male the application much much more complicated and we would also need to store some data and token (we do not even have a database currently).

I'm afraid this feature will then not be implemented in a near future. But thanks anyway for your ideas :slightly_smiling_face:

**Comment by damienalexandre** [comment]
Agreed with @pyrech but lets keep this issue open to collect :+1: reactions :pray: 

Thanks!

**Comment by nclm** [comment]
Ah yes I can see how that can be an issue, thanks for the reply!

**Comment by damienalexandre** [comment]
Some good news about this: we can implement this quite easily for Slack: https://api.slack.com/messaging/scheduling

**Comment by damienalexandre** [comment]
We forgot to tell you, it's done!

![image](https://user-images.githubusercontent.com/225704/202926946-79321362-01c6-4f5a-9335-d0dc18dd416c.png)

Happy secret santa!
