### ISSUE TITLE
Slack permission "email" is requested for nothing

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#123]
We have a long lasting issue with Slack Apps requesting the **email scope**, even if we dont request it (we request **users:read**). Last February we got this answer from them:

> Hi again Damien,
> I am sorry to report that we are not able to remove the scoped email access that your app currently has been granted due to the older users:read scope.
> We do not have a timeline on when we will be adjusting this from our side, and as far as I know, the only workaround is to create a new app (losing currently installations if you fully delete that app) and start fresh with a newly created app that won't have the same issues.
> Apologies for the bad news here. Let me know if you have any other thoughts/questions.
> Thanks,
> xxx

So just because the app was created a long time ago, the email address is always asked for and this can't be removed.

More than a year after, I tried the suggestion to create a new app. Here is the results:

# Actual application

![image](https://user-images.githubusercontent.com/225704/66044603-36a5e000-e522-11e9-95bf-49520dd65d41.png)

# New unpublished application

![image](https://user-images.githubusercontent.com/225704/66044329-90f27100-e521-11e9-8679-2ee21f282633.png)

# Conclusions

If we want to get rid of the **View email addresses of people on your workspace** permission, our only solution is to create a brand new application on Slack Apps, and go through the complete publication procedure.

**Comment by pyrech** [comment]
Fixed \o/
