### ISSUE TITLE
Warning on the UserExtractor

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#134]
Seen in the logs:

> 2019-11-15T12:49:07+01:00 [:error] [pid 1169:tid 139881523087104] [client 46.252.181.103:37412] FastCGI: server "/var/www/php5-fpm/php5.external" stderr: PHP message: [2019-11-15 11:49:05] php.WARNING: Warning: Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /home/bas/app_2e11a7d1-37ca-4bd1-8b51-083011a69f18/src/Slack/UserExtractor.php:108)"} [], referer: https://secret-santa.team/

**Comment by pyrech** [comment]
Closing as nothing similar happened since
