### ISSUE TITLE
Use Apache instead of Ngnix for the local docker setup

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#159]
Our hosting provider is using Apache 2, but our Docker stack is using Ngnix, making it harder to resolve issues with .htaccess.

cc @HedicGuibert SORRY! :smile:

**Comment by m8051** [comment]
Hi @damienalexandre I'd like to pick up this one, I believe I could help. May I?

**Comment by damienalexandre** [comment]
Yes feel free, I will assign you.

For more context this project use https://github.com/jolicode/docker-starter as a base.
Our "frontend" service use Ngnix at the moment.
https://github.com/jolicode/secret-santa/blob/736383624b03a23a30d29f99c4a4e7bef3bed2f3/infrastructure/docker/services/frontend/Dockerfile

We must use Apache2, same as our hosting provider: https://www.clever-cloud.com/doc/php/php-apps/

So this ticket is about changing our Frontend Docker image. I will assign you :+1:

**Comment by m8051** [comment]
Hi @damienalexandre: I created a PR that attempts to help with this issue, let me know your thoughts.

Thanks in advance.
