### ISSUE TITLE
Long messages cannot be sent on Slack and Discord

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#177]
There is a Block API limit:

https://api.slack.com/reference/block-kit/blocks#section_fields

> The text for the block, in the form of a text object. Maximum length for the text in this field is 3000 characters. This field is not required if a valid array of fields objects is provided instead.

We have some errors:

> Slack returned error code "invalid_blocks"

We must add a limit.

**Comment by pyrech** [comment]
Discord also limits the length of the message to 2000 chars, so the admin message need to contain less than 1300 chars ( we have some text around that can already lot of chars.

At first I propose to just add a limit of 1000 chars for the admin message for each app. If the need for longer messages is really wanted, we could still fine-tuned later the limit according to each app's limit.
