### ISSUE TITLE
Update TLS version on production

### ISSUE THREAD

**Issue by pyrech** [jolicode/secret-santa#212]
A security from Zoom marketplace informed us that it seems we use an obselete tls version.

> Transport Layer Security versions TLS1.0 and TLS1.1 are obsolete

We need to find if this is something we can configure on our hosting provider (https://www.clever-cloud.com/doc/)

**Comment by xavierlacot** [comment]
Obviously the website of Clever Cloud itself only uses TLS 1.2+, so it must be possible

**Comment by Nispeon** [comment]
We are using TLS 1.3, the problem is that we should disallow version 1.0 and 1.1 compatibility. It is most definitely something that has to be dealt with by sending a ticket to their support, as it is not doable from the Clever Cloud dashboard.

**Comment by damienalexandre** [comment]
From the support:

> We will deprecate those TLS versions in the end of the year [...]

Just wait a see :sunglasses:

**Comment by damienalexandre** [comment]
![image](https://user-images.githubusercontent.com/225704/196045904-80f11865-3298-49f0-9845-d0b2c0e0ee66.png)

It's fixed upstream :+1:
