### ISSUE TITLE
Allow to set an exception list to avoid some gifter => giftee couples

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#253]
We could add a way to forbid some association in the shuffle.

From our support email:

> Ever since my group of friends decided to do Secret Santa I have used your app and it has helped a ton in making organisation a lot easier. As we continue to do this, I would like to ensure that people aren't getting the same people they've gave a gift to the previous year, so I was wondering if it was possible to make some sort of exception list to make sure that certain people don't get matched with other certain people. I believe this would be a great addition to your already amazing bot.

Could also prove useful when you do a family event and you don't want family members from the same household to be assigned to each other.

From an UI point of view, it may be quite a challenge as we don't want to complicate the setup too much.

**Comment by pyrech** [comment]
duplicates #144
