### ISSUE TITLE
Fix the Content Security Policy to allow avatars display and JavaScript

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/secret-santa#73]
Avatars are not displayed anymore:

![image](https://user-images.githubusercontent.com/225704/44958515-b60d4e00-aee1-11e8-851e-ac171b3c2795.png)

Our pages send this header: `Content-Security-Policy: default-src 'self'; base-uri 'self';` so the avatars gets blocked:

![image](https://user-images.githubusercontent.com/225704/44958531-cc1b0e80-aee1-11e8-8944-df425853a493.png)

Also, inline JavaScript is not executed:

> Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-SYgPl6GxmNtUIiPe4ASGGixmj9g/tOP622WecLQi6Qo='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

So... Nothing works right now.

**Comment by pyrech** [comment]
For some reasons, it's still working on my Firefox, hence didn't see those errors :confused:. It fixed now
