### ISSUE TITLE
Increase Slack API calls timeout

### ISSUE THREAD

**Issue by pyrech** [jolicode/secret-santa#78]
A lot of Slack API calls are failing these days. It looks like it's related to a network timeout :

```
cURL error 28: Operation timed out after 2001 milliseconds with 0 bytes received
```

We should probably make the timeout greater than 2 seconds (5 or 10s should be fine)

**Comment by lamar-frankie** [comment]
I would like to claim this issue.

**Comment by pyrech** [comment]
Yep, of course, you can give it a try. Let us know if you need some help :wink:

**Comment by Lilja** [comment]
Should be closed?

**Comment by pyrech** [comment]
Indeed :+1:
